# Generated by Django 3.2.4 on 2021-07-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='body',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='image',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='title',
        ),
        migrations.AddField(
            model_name='thesis',
            name='crypto',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
