# Generated by Django 3.2.4 on 2021-07-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_auto_20210724_2352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thesis',
        ),
    ]
