# Generated by Django 3.2.4 on 2021-07-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_achievement_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
